spring.application.name=Github-CI-CD-Action
server.port=8181

# ==============================
# PostgreSQL / AWS RDS
# ==============================

# AWS RDS PostgreSQL
spring.datasource.url=jdbc:postgresql://database-1.cbuykq0wk3l3.ap-southeast-2.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Vivekpandeycloud
spring.datasource.driver-class-name=org.postgresql.Driver


# ==============================
# JPA / Hibernate
# ==============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# ==============================
# Actuator
# ==============================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


# ==============================
# Swagger
# ==============================

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
