spring.application.name=Github-CI-CD-Action
server.port=8181

# ===============================
# PostgreSQL
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Actuator
# ===============================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
